title: Chenyang Zhao
description: Currently pursuing a Master of Engineering at UVic, building on three years of prior experience as a Front-End Development Engineer at JD.com
show_downloads: true
theme: jekyll-theme-minimal
