title: Chenyang Zhao
description: Curently a student in Master of Engineerin, Telecommunications & Information Security at UVic, with a solid three-year experience as a Front-End Development Engineer at JD.com
show_downloads: true
theme: jekyll-theme-minimal
