title: Leah(Chenyang) Zhao
logo: /assets/334521699600525_.pic_hd.jpg
# description: Building on over three years of experience as a Front-End Development Engineer at JD.com, I have honed my skills in creating advanced, user-friendly web interfaces and contributing to large-scale projects.
show_downloads: true
theme: jekyll-theme-minimal
